package com.unemployedlistening.analysis;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

import org.apache.hadoop.conf.Configuration;
import org.apache.hadoop.conf.Configured;
import org.apache.hadoop.fs.FileSystem;
import org.apache.hadoop.fs.Path;
import org.apache.hadoop.util.Tool;
import org.apache.hadoop.util.ToolRunner;

/**
 * Predicts which genres will become more or less prevalent based on changes in
 * unemployment.
 * Uses correlation data generated by CorrelationAnalyzer to make predictions.
 * 
 * Input: Correlation analysis file and previous/current unemployment rates
 * Output: Predictions for genre prevalence changes
 */
public class GenrePredictor extends Configured implements Tool {

    private static class GenreCorrelation {
        String genre;
        double correlation;
        int dataPoints;

        GenreCorrelation(String genre, double correlation, int dataPoints) {
            this.genre = genre;
            this.correlation = correlation;
            this.dataPoints = dataPoints;
        }
    }

    @Override
    public int run(String[] args) throws Exception {
        if (args.length < 3) {
            System.err.println("Usage: GenrePredictor <correlation_file> <prev_unemployment> <curr_unemployment>");
            System.err.println("  correlation_file: Path to correlation analysis output");
            System.err.println("  prev_unemployment: Previous year's unemployment rate (e.g., 4.5)");
            System.err.println("  curr_unemployment: Current year's unemployment rate (e.g., 5.2)");
            return 1;
        }

        String correlationFile = args[0];
        double prevUnemployment = Double.parseDouble(args[1]);
        double currUnemployment = Double.parseDouble(args[2]);

        double unemploymentChange = currUnemployment - prevUnemployment;

        Configuration conf = getConf();
        FileSystem fs = FileSystem.get(conf);

        // Load correlation data
        List<GenreCorrelation> correlations = loadCorrelations(fs, new Path(correlationFile));

        // Make predictions
        makePredictions(correlations, prevUnemployment, currUnemployment, unemploymentChange);

        return 0;
    }

    // Load correlation data from analysis output file
    private List<GenreCorrelation> loadCorrelations(FileSystem fs, Path path) throws IOException {
        List<GenreCorrelation> correlations = new ArrayList<>();

        try (BufferedReader reader = new BufferedReader(
                new InputStreamReader(fs.open(path)))) {
            String line;
            boolean header = true;

            while ((line = reader.readLine()) != null) {
                // Skip header
                if (header) {
                    header = false;
                    continue;
                }

                line = line.trim();
                if (line.isEmpty())
                    continue;

                String[] parts = line.split("\t");
                if (parts.length < 3)
                    continue;

                try {
                    String genre = parts[0].trim();
                    double correlation = Double.parseDouble(parts[1].trim());
                    int dataPoints = Integer.parseInt(parts[2].trim());

                    // Only include genres with enough data points for reliable predictions
                    if (dataPoints >= 5) {
                        correlations.add(new GenreCorrelation(genre, correlation, dataPoints));
                    }
                } catch (NumberFormatException e) {
                    // Skip malformed lines
                }
            }
        }

        return correlations;
    }

    // Generate and print predictions based on unemployment change
    private void makePredictions(List<GenreCorrelation> correlations,
            double prevUnemployment,
            double currUnemployment,
            double unemploymentChange) {

        System.out.println("\n=== Genre Prevalence Prediction ===\n");
        System.out.println(String.format("Previous Unemployment: %.2f%%", prevUnemployment));
        System.out.println(String.format("Current Unemployment:  %.2f%%", currUnemployment));
        System.out.println(String.format("Change:                %+.2f%%", unemploymentChange));

        if (Math.abs(unemploymentChange) < 0.1) {
            System.out.println("\nUnemployment change is minimal. No significant genre shifts expected.");
            return;
        }

        String direction = unemploymentChange > 0 ? "INCREASING" : "DECREASING";
        System.out.println(String.format("\nUnemployment is %s\n", direction));

        // Separate genres into those expected to increase vs decrease
        List<GenreCorrelation> expectedIncrease = new ArrayList<>();
        List<GenreCorrelation> expectedDecrease = new ArrayList<>();

        for (GenreCorrelation gc : correlations) {
            // Skip weak correlations
            if (Math.abs(gc.correlation) < 0.2) {
                continue;
            }

            // Positive correlation + unemployment increase = genre increase
            // Positive correlation + unemployment decrease = genre decrease
            // Negative correlation + unemployment increase = genre decrease
            // Negative correlation + unemployment decrease = genre increase

            boolean willIncrease = (gc.correlation > 0 && unemploymentChange > 0) ||
                    (gc.correlation < 0 && unemploymentChange < 0);

            if (willIncrease) {
                expectedIncrease.add(gc);
            } else {
                expectedDecrease.add(gc);
            }
        }

        // Sort by correlation strength
        expectedIncrease.sort(Comparator.comparingDouble(g -> -Math.abs(g.correlation)));
        expectedDecrease.sort(Comparator.comparingDouble(g -> -Math.abs(g.correlation)));

        // Print predictions
        System.out.println("Genres Expected to INCREASE in Prevalence:");
        System.out.println(String.format("%-20s %15s %15s", "Genre", "Correlation", "Confidence"));
        System.out.println("-".repeat(55));

        if (expectedIncrease.isEmpty()) {
            System.out.println("(No genres with significant positive prediction)");
        } else {
            for (GenreCorrelation gc : expectedIncrease) {
                String confidence = getConfidenceLevel(gc.correlation, gc.dataPoints);
                System.out.println(String.format("%-20s %+15.4f %15s",
                        gc.genre, gc.correlation, confidence));
            }
        }

        System.out.println("\nGenres Expected to DECREASE in Prevalence:");
        System.out.println(String.format("%-20s %15s %15s", "Genre", "Correlation", "Confidence"));
        System.out.println("-".repeat(55));

        if (expectedDecrease.isEmpty()) {
            System.out.println("(No genres with significant negative prediction)");
        } else {
            for (GenreCorrelation gc : expectedDecrease) {
                String confidence = getConfidenceLevel(gc.correlation, gc.dataPoints);
                System.out.println(String.format("%-20s %+15.4f %15s",
                        gc.genre, gc.correlation, confidence));
            }
        }

        System.out.println("\nNote: Predictions are based on historical correlations.");
        System.out.println("Correlation does not imply causation.");
        System.out.println("Higher data points and stronger correlations indicate more reliable predictions.");
    }

    // Determine confidence level based on correlation strength and data points
    private String getConfidenceLevel(double correlation, int dataPoints) {
        double absCorr = Math.abs(correlation);

        if (absCorr > 0.6 && dataPoints >= 20) {
            return "HIGH";
        } else if (absCorr > 0.4 && dataPoints >= 10) {
            return "MEDIUM";
        } else {
            return "LOW";
        }
    }

    public static void main(String[] args) throws Exception {
        int exitCode = ToolRunner.run(new Configuration(), new GenrePredictor(), args);
        System.exit(exitCode);
    }
}
